/ taskpy: taskweek: needs to pass arg to taskday as string
when we pass in the arg as an integer, it won't with with argparse, the
following stack trace occurs when we pass *args:

 $ .task/taskweek
 Traceback (most recent call last):
   File "/home/scott/.task/taskweek", line 478, in <module>
     try: main()
   File "/home/scott/.task/taskweek", line 450, in main
     instcnt = subprogram(*args)
   File "/home/scott/.task/taskweek", line 225, in taskweek
     def taskweek(): taskday(7)
   File "/home/scott/.task/taskweek", line 241, in taskday
     args = argp.parse_args(args)
   File "/opt/python-3.9.5/lib/python3.9/argparse.py", line 1818, in parse_args
     args, argv = self.parse_known_args(args, namespace)
   File "/opt/python-3.9.5/lib/python3.9/argparse.py", line 1851, in parse_known_args
     namespace, args = self._parse_known_args(args, namespace)
   File "/opt/python-3.9.5/lib/python3.9/argparse.py", line 1895, in _parse_known_args
     option_tuple = self._parse_optional(arg_string)
   File "/opt/python-3.9.5/lib/python3.9/argparse.py", line 2182, in _parse_optional
     if not arg_string[0] in self.prefix_chars:
 TypeError: 'int' object is not subscriptable

needs to be a string like it would be if taken from the command line