- taskw: move taskw.py to task.py because we import taskw lib
without it we get something like this when running manually prior to install:

 $ ./taskget 1
Traceback (most recent call last):
  File "/home/scott/.task/./taskget", line 27, in <module>
    from taskw import TaskWarrior
  File "/home/scott/.task/taskw.py", line 27, in <module>
    from taskw import TaskWarrior
ImportError: cannot import name 'TaskWarrior' from partially initialized module
'taskw' (most likely due to a circular import) (/home/scott/.task/taskw.py)

this collides with taskw lib.  we could do something with namespaces or
absolute imports, but it's easier to just rename our script.